name: merceria_app
description: A new Flutter project.
publish_to: 'none'
version: 2.0.3+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.1.3
  http:
  curved_navigation_bar:
  flutter_html:
  animated_splash_screen:
  flutter_launcher_icons:
  cupertino_icons: ^1.0.2

flutter_icons:
  image_path: "assets/android/ic_launcher.png"
  ios: true
  android: "launcher_icon"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
